name: ReactJS build CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Installing dependencies
              run: npm ci

            - name: Deploying to GH-Pages
              run: |
                  echo ${{ secrets.ACCESS_TOKEN }}
                  git config --global user.email "61000207+shivamsingh-07@users.noreply.github.com"
                  git config --global user.name "shivamsingh-07"
                  git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/shivamsingh-07/react-app.git
                  npm run deploy
