name: Build Docker Image

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Publishing new package
              run: |
                  echo ${{ secrets.ACCESS_TOKEN }} | docker login https://docker.pkg.github.com --username shivamsingh-07 --password-stdin
                  docker build -t react-app:latest .
                  docker tag react-app:latest docker.pkg.github.com/shivamsingh-07/react-app/reactjs:1.0
                  docker push docker.pkg.github.com/shivamsingh-07/react-app/reactjs:1.0
